apiVersion: v1
data:
  CACHE_SHARED: "true"
  CI_SERVER_URL: "[YOUR_GITLAB_URL]"
  KUBERNETES_CPU_LIMIT: 800m
  KUBERNETES_CPU_REQUEST: 200m
  KUBERNETES_IMAGE_PULL_SECRETS: "[YOUR_PRIVATE_DOCKER_REGISTRY_PULL_SECRETS]"
  KUBERNETES_MEMORY_LIMIT: 800Mi
  KUBERNETES_MEMORY_REQUEST: 200Mi
  KUBERNETES_NAMESPACE: "[YOUR_GITLAB_NAMESPACE]"
  KUBERNETES_POLL_INTERVAL: "5"
  KUBERNETES_POLL_TIMEOUT: "360"
  KUBERNETES_PULL_POLICY: if-not-present
  KUBERNETES_TERMINATIONGRACEPERIODSECONDS: "10"
  REGISTER_LOCKED: "false"
  REGISTER_NON_INTERACTIVE: "true"
  REGISTER_RUN_UNTAGGED: "true"
  RUNNER_EXECUTOR: kubernetes
  RUNNER_REQUEST_CONCURRENCY: "3"
  RUNNER_TAG_LIST: TAG_1, TAG_2
kind: ConfigMap
metadata:
  labels:
    app: gitlab-ci-runner
  name: gitlab-ci-runner-cm
  namespace: [YOUR_GITLAB_NAMESPACE]

---

apiVersion: v1
data:
  run.sh: |
    #!/bin/bash
    unregister() {
        kill %1
        echo "Unregistering runner ${RUNNER_NAME} ..."
        /usr/bin/gitlab-ci-multi-runner unregister -t "$(/usr/bin/gitlab-ci-multi-runner list 2>&1 | tail -n1 | awk '{print $4}' | cut -d'=' -f2)" -n ${RUNNER_NAME}
        exit $?
    }
    trap 'unregister' EXIT HUP INT QUIT PIPE TERM
    echo "Registering runner ${RUNNER_NAME} ..."
    /usr/bin/gitlab-ci-multi-runner register -r ${GITLAB_CI_TOKEN}

    sed -i 'N;/runners.cache/a\    Type = "s3"' /home/gitlab-runner/.gitlab-runner/config.toml

    sed -i 'N;/runners.cache.s3/a\    ServerAddress = "s3.cn-north-1.amazonaws.com.cn"\n    AccessKey = "[YOUR_AWS_ACCESS_KEY]"\n    SecretKey = "[YOUR_AWS_ACCESS_SECRET]"\n    BucketName = "[YOUR_AWS_S3_BUCKET]"\n    BucketLocation = "[YOUR_AWS_S3_LOCATION]"' /home/gitlab-runner/.gitlab-runner/config.toml

    sed -i 's/^concurrent.*/concurrent = '"${RUNNER_REQUEST_CONCURRENCY}"'/' /home/gitlab-runner/.gitlab-runner/config.toml
    echo "Starting runner ${RUNNER_NAME} ..."
    /usr/bin/gitlab-ci-multi-runner run -n ${RUNNER_NAME} &
    wait
kind: ConfigMap
metadata:
  labels:
    app: gitlab-ci-runner
  name: gitlab-ci-runner-scripts
  namespace: gitlab
