apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-ci
  namespace: [YOUR_GITLAB_NAMESPACE]
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: [YOUR_GITLAB_NAMESPACE]
  name: gitlab-ci
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitlab-ci
  namespace: [YOUR_GITLAB_NAMESPACE]
subjects:
  - kind: ServiceAccount
    name: gitlab-ci
    namespace: [YOUR_GITLAB_NAMESPACE]
roleRef:
  kind: Role
  name: gitlab-ci
  apiGroup: rbac.authorization.k8s.io
